[logger]
    mode = "debug"
    timestamp = "time"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = false
    env = "development"
    [api.parsing]
        enable = true

[web]
    enable = true
    auth = false
    [web.static]
        folder = "static"