[logger]
    mode = "debug"
    timestamp = "none"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = true
    env = "development"